# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-18.04"
    config.vm.synced_folder "../", "/etc/ansible/roles/test"

    config.vm.provider "virtualbox" do |vbox|
        vbox.memory = 512
        vbox.cpus   = 1
    end

    config.vm.provision "shell", path: "Vagrantboot"

    config.vm.provision "ansible_local" do |ansible|
        ansible.inventory_path    = "inventory"
        ansible.playbook          = "test.yml"
        ansible.limit             = "all"
    end
end
